name: New Idea !
description: just developing something
meta_description: "programming about game"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.ekocaman.com'

# Details for the RSS feed generator
url:            'www.ekocaman.com'
author:         'Erol KOCAMAN'
